# Generated by Django 6.1 on 2026-09-21 08:32

import django.db.models.deletion
import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Aadhar_Details",
            fields=[
                (
                    "number",
                    models.CharField(
                        default=home.models.generate_aadhaar_number,
                        editable=False,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("First_name", models.CharField(max_length=32)),
                ("Middle_name", models.CharField(blank=True, max_length=32)),
                ("Last_name", models.CharField(max_length=32)),
                ("dob", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Others")],
                        max_length=1,
                    ),
                ),
                ("Father_name", models.CharField(max_length=50)),
                ("Phone_number", models.PositiveBigIntegerField(unique=True)),
                ("photo", models.ImageField(blank=True, upload_to="profiles")),
                ("address", models.TextField()),
                ("pincode", models.IntegerField()),
                (
                    "state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.state"
                    ),
                ),
            ],
        ),
    ]
