# Generated by Django 6.1 on 2026-09-21 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="state",
            options={"ordering": ["name"]},
        ),
    ]
